config/routes.rb
Rails.application.routes.draw do
  resources :stars

end

app/models/star.rb
class Star < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stars_controller.rb
class StarsController < ApplicationController
  before_action :set_star, only: [:show, :edit, :update, :destroy]

  # GET /stars
  # GET /stars.json
  def index
    @stars = Star.all
  end

  # GET /stars/1
  # GET /stars/1.json
  def show
  end

  # GET /stars/new
  def new
    @star = Star.new
  end

  # GET /stars/1/edit
  def edit
  end

  # POST /stars
  # POST /stars.json
  def create
    @star = Star.new(star_params)

    respond_to do |format|
      if @star.save
        format.html { redirect_to @star, notice: 'Star was successfully created.' }
        format.json { render :show, status: :created, location: @star }
      else
        format.html { render :new }
        format.json { render json: @star.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stars/1
  # PATCH/PUT /stars/1.json
  def update
    respond_to do |format|
      if @star.update(star_params)
        format.html { redirect_to @star, notice: 'Star was successfully updated.' }
        format.json { render :show, status: :ok, location: @star }
      else
        format.html { render :edit }
        format.json { render json: @star.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stars/1
  # DELETE /stars/1.json
  def destroy
    @star.destroy
    respond_to do |format|
      format.html { redirect_to stars_url, notice: 'Star was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_star
      @star = Star.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def star_params
      params.require(:star).permit(:user_id, :url, :quatation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stars_helper.rb
module StarsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title RailsTemplate
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = yield

app/views/stars/_form.html.slim
= form_for @star do |f|
  - if @star.errors.any?
    #error_explanation
      h2 = "#{pluralize(@star.errors.count, "error")} prohibited this star from being saved:"
      ul
        - @star.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :url
    = f.text_area :url
  .field
    = f.label :quatation
    = f.text_field :quatation
  .actions = f.submit 'Save'

app/views/stars/edit.html.slim
h1 Editing star

== render 'form'

= link_to 'Show', @star
'|
= link_to 'Back', stars_path

app/views/stars/index.html.slim
h1 Listing stars

table
  thead
    tr
      th User
      th Url
      th Quatation
      th
      th
      th

  tbody
    - @stars.each do |star|
      tr
        td = star.user_id
        td = star.url
        td = star.quatation
        td = link_to 'Show', star
        td = link_to 'Edit', edit_star_path(star)
        td = link_to 'Destroy', star, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Star', new_star_path

app/views/stars/new.html.slim
h1 New star

== render 'form'

= link_to 'Back', stars_path

app/views/stars/show.html.slim
p#notice = notice

p
  strong User:
  = @star.user_id
p
  strong Url:
  = @star.url
p
  strong Quatation:
  = @star.quatation

= link_to 'Edit', edit_star_path(@star)
'|
= link_to 'Back', stars_path